// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RaynMaker.Modules.Browser")]
[assembly: AssemblyProductAttribute("RaynMaker")]
[assembly: AssemblyDescriptionAttribute("RaynMaker")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("1.9.0.0")]
[assembly: AssemblyFileVersionAttribute("1.9.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "RaynMaker.Modules.Browser";
        internal const System.String AssemblyProduct = "RaynMaker";
        internal const System.String AssemblyDescription = "RaynMaker";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "1.9.0.0";
        internal const System.String AssemblyFileVersion = "1.9.0.0";
    }
}
